version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
